---
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: teamcity
  region: eu-west-1
  availability_zone: eu-west-1a

provisioner:
  name: chef_solo

platforms:
  - name: debian-8-docker
    driver:
      name: docker
      use_sudo: false
      image: debian:8.0
  - name: centos-7-vagrant
    driver:
      name: vagrant
      box: centos-7
      box_url: 'https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box'
  - name: centos-7-ec2
    driver:
      name: ec2
      image_id: ami-e4ff5c93 
      instance_type: t2.micro
      transport.username: centos
      transport.ssh_key: teamcity.pem
suites:
  - name: default
    run_list: ['teamcity-cookbook']
    attributes:
